### ISSUE TITLE
Query all nodes of a specific label using strong typed vertex

### ISSUE THREAD

**Issue by direbearform** [evo-terren/Gremlin.Net.CosmosDb#12]
g.V<T>() only does casting but not filtering by label
g.V().HasLabel(string name) requires label parameter which then one has to write their own LabelName.Resolve (Which is internal)

I wonder what would you suggest here? Either we can make a hasLabel extension that resolve the label name without needing the parameter or you might have suggest better way to do this?

**Comment by evo-terren** [comment]
Hmm. Yes this does seem like an oversight on my part. 

In general, I am hesitant to add traversals that are "hidden" from the code, but in this case, I think g.V<TVertex>() should add the hasLabel() step accordingly (as well as g.E<TEdge>()). Adding that in would match semantically what a programmer would expect. 

I'm happy to accept a pull request if you would like to do this. Otherwise, I should be able to get to it tomorrow morning.

**Comment by direbearform** [comment]
Thanks for looking into this. PR created.

**Comment by direbearform** [comment]
Bummer, that was an embarrassing copy-paste. Updated.
