### ISSUE TITLE
Strong typed OutE takes 0 parameter

### ISSUE THREAD

**Issue by direbearform** [evo-terren/Gremlin.Net.CosmosDb#15]
Seems a parameter-less OutE would be rather useful.

I propose to add sth like this, what do you think?

```
public static ISchemaBoundTraversal<object, T> OutE<TS, T>(this ISchemaBoundTraversal<object, TS> traversal)
    where T : EdgeBase
    {
        var labelAttr = typeof(T).GetCustomAttributes(typeof(LabelAttribute), true).OfType<LabelAttribute>().FirstOrDefault();
        var labelName = labelAttr?.Name;
        var graphTraversal = new GraphTraversal<object, T>(new ITraversalStrategy[0], new Bytecode(traversal.Bytecode));
            
        return graphTraversal.OutE(labelName).Cast<T>();
    }
```

**Comment by evo-terren** [comment]
I went down this road when originally implementing what I have so far and decided against this approach for three reasons (bear with me while I explain):

1. I'm not crazy about the idea of faking the first parameter of the schema bound traversal with `object`. Quite frankly, I think the first one is superfluous and have no idea why the `GraphTraversal<S, T>` defines S. It seems to do nothing, yet the Gremlin.Net code has it in there. If I was going to completely deviate and write my own standalone library, I would most certainly remove that parameter. But until I do, I'm at least going to be a diligent programmer and try to keep that thing around the best I can. I know that I've made some short cuts in some of the code, but that was only because I could find no way around it.
2. I specifically built `EdgeBase<ToutV, TinV>` so that the templated parameters (ToutV and TinV) can always give compile-time errors when a programmer attempts to traverse with that edge using any other vertex types. This way, if you have two vertices that are very similar in names, you don't run the risk of accidentally typing one while you really meant to type the other and finding the bug later on in the development process. I'd rather get the error at compile-time and fix my mistake immediately. It seems like your head is kind of "in schema mode" when you design your edge and vertex classes, but more "in traversal mode" when actually programming out the traversals, so it feels like the compile-time error is more applicable. Allowing `T : EdgeBase` doesn't really restrict anything.
3. Lastly, having to specify the vertex type as a type parameter when using your method above seems a little clunky to me: `g.V<SomeVertex>(myUniqueId).OutE<SomeVertex, SomeEdge>()` seems like it's redundant (I had to type `SomeVertex` twice). I'd rather type `g.V<SomeVertex>(myUniqueId).OutE(v => v.SomeEdge)`.
