### ISSUE TITLE
Subquery is not correctly serialized in ToGremlinQuery

### ISSUE THREAD

**Issue by direbearform** [evo-terren/Gremlin.Net.CosmosDb#16]
E.g. 
g.V().and(__.something, __.something2).

If I construct using ISchemaBoundQuery and with ToGremlinQuery, I got something like this instead:
"g.V().and(something, something2)", without the __. prefix.

I don't know Gremlin enough to know if there are other situations exist, but I feel in this case, the Serialize(ITraversal) function should append __. in front.

One possible way to force this behavior is to allow the creation of a GraphTraversal that adds the source of "__" in the place of "g". 

Assume we do this in IGraphClient next to CreateTraversalSource() call (may not be best choice, you tell me), then we write code like this:

GetClient().CreateTraversalSource().V().And(GetClient().CreateSubTraversalSource(). ..., GetClient().CreateSubTraversalSource(). ..., )

What do you think? If you agree I can attempt a pull request.

**Comment by evo-terren** [comment]
Yep. My team and I have encountered this issue as well. One thing we've noticed is that Cosmos Db doesn't seem to be consistent on whether the `__` should be specified or not. More often than not, it doesn't seem to matter, but sometimes you must specify the `__` and other times you must not. It's also hard to put all the blame on Microsoft since they don't "[officially support all traversal steps yet](https://docs.microsoft.com/en-us/azure/cosmos-db/gremlin-support#gremlin-steps)".

I think the best approach to solving this one with code (at least until Microsoft figures things out on their end) would be to add an overload to `CreateTraversalSource()` which accepts either a string (to allow anything) or an enum (to allow only `g`, `__` or "anonymous"/"blank"). Utilizing an enum would probably be preferred. This would allow you to locally define what you need in a particular situation:

```
var g = graphClient.CreateTraversalSource(); //equivalent to CreateTraversalSource("g")
var __ = graphClient.CreateTraversalSource("__");
var anon = graphClient.CreateTraversalSource(String.Empty); //seems a little weird here...

var query = g.V().And(__.OutE(), anon.InE());

Console.WriteLine(query.ToGremlinQuery()); //g.V().and(__.outE(), inE())
```

@evo-thomas, do you have any input on this one? You were the one who just ran into this same thing.

**Comment by evo-thomas** [comment]
Yea, what you said is pretty accurate.  The `__` prefix is required when starting with reserved keywords such as `in` or `by`, because Gremlin queries are parsed as Groovy.  It's also required to prefix certain traversals, such as `V()`.

I don't remember for sure if there are any cases where using the `__` prefix would cause an issue, though.

**Comment by evo-thomas** [comment]
I'd also like to note that `Gremlin.NET` itself does not add a traversal step for `__`, so this may be an underlying issue with that library.

**Comment by SamHard** [comment]
I came up with a solution that I think works pretty well.  It is seamless to the user.  What I did was to keep track in the GremlinQuerySerializer when a traversal is started as an argument to another step, and I created a list of steps that are known to require the prefix "__" when used in an anonymous traversal.

@evo-terren, if you would please give me permission to create a branch, I'll push my changes and create a pull request.
