### ISSUE TITLE
Support Script Parameterization to avoid Gremlin Injection

### ISSUE THREAD

**Issue by jpamp** [evo-terren/Gremlin.Net.CosmosDb#21]
I stumbled across [this SO](https://stackoverflow.com/questions/44473303/how-to-prevent-gremlin-injection-in-c) question and was wondering how this could be supported with the GremlinQuerySerializer.

**Comment by evo-terren** [comment]
I'm not sure it would be necessary since c# should be escaping the string already. Have you been able to inject traversals into the query? I can't figure out how it could be done. If you can figure out a way, please let me know with some code samples and I'll give some thought as to how the bindings could be used.

The only thing that I'm aware of that would allow for bindings to be beneficial is their performance/caching benefit: http://tinkerpop.apache.org/docs/current/reference/#_bindings_2. I haven't been able to do any performance testing to see just how much this impacts performance.

Let me know your findings!

**Comment by evo-terren** [comment]
Feel free to re-open this issue if you are able to inject some gremlin code. Otherwise, I'm going to consider this resolved.

**Comment by jpamp** [comment]
I haven't tried the injection, but I think you are correct.  This would be just be an enhancement, if implemented.
