### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by oysteingl** [evo-terren/Gremlin.Net.CosmosDb#28]
Have you found any way to use the transaction API for tinkerpop (http://tinkerpop.apache.org/docs/current/reference/#transactions), or any other alternative solutions?

**Comment by evo-terren** [comment]
So from a true transaction standpoint (with commit/rollback support), I haven't been able to figure out how to get transactions to work with CosmosDb. They're not listed as supported features [anywhere in their documentation](https://docs.microsoft.com/en-us/azure/cosmos-db/gremlin-support), nor does their interactive gremlin console suggest that any of the transaction methods (`tx()`, `commit()`, `isOpen()`, etc.).

That being said, my team and I have had transaction-like needs and have figured out a workaround that seems to have worked for us. For our purposes, we needed a way to query existing vertices, perform checks on their property values to ensure they hadn't changed from what was expected and then perform the updates/deletes/etc. we needed, all while being able to detect which check(s) failed during the query so that we could return verbose exceptions appropriately. By utilizing the `project()` and `by()` traversal steps, we have been able to do all of this in single queries with quasi-optimistic concurrency.

I'll illustrate using some examples - hopefully this will be clear enough to you. Assume we have the following strongly-typed vertex:

```c#
[Label("VersionedVertex")]
public class VersionedVertex : VertexBase
{
    public string Content { get; set; }
    public string ETag { get; set; }
}
```

Here we have created a vertex that defines a `Content` property that represents something meaningful we want to get/update and an `ETag` property, which can be used as a way to similarly to the http request feature with the same name. Ideally, the etag will contain a value that can be used to maintain optimistic concurrency across queries. You can populate this value however you want - we've been using GUIDs.

So, let's first add an instance of our versioned vertex:

```c#
var vertex = new VersionedVertex { Id = "your-id", Content = "Some interesting content", ETag = "version-1" };
var g = graph.CreateTraversalSource();
await graph.ExecuteAsync(g.AddV(vertex));
```

As long as a calling client has the current etag value ("version-1"), we can safely update the content to something new like so:

```c#
//build unique traversals for each check you need
var etagCheck = __.Start().Cast<VersionedVertex>()
                              .Has(v => v.ETag, "version-1")
                              .Count();

var updateQuery = g.V<VersionedVertex>("your-id")
                                  .Project<long>(nameof(etagCheck), "performUpdate")
                                  .By(etagCheck)
                                  .By(__.Start().Cast<VersionedVertex>()
                                       //use filters for each check before performing update
                                       .Where(etagCheck.Clone().Is(1))
                                       .Property(v => v.Content, "Updated content value")
                                       .Property(v => v.ETag, "version-2")
                                       .Count()
                                 );

var result = await graph.QuerySingleOrDefaultAsync(updateQuery);

//if the result is null, this means that the initial g.V('your-id') returned no results
if (result == null)
    throw new UnknownIdentifierException();

//utilize the counts returned in the projection
//to tell you which of the check(s) failed
if (result[nameof(etagCheck)] != 1)
    throw new ConcurrencyException();
```

I realize how complex this may seem, but hopefully it makes sense to you. Basically, build unique traversals for each kind of check you need before you can safely execute your update/delete. Hopefully you can distill each check down to using `Count()` at the end so that your projection can use `long` as its return type. If you can't do this, just use `JToken` instead and do last minute parsing when throwing your exceptions. You can chain multiple checks by extending your project step like so: 

```c#
g.V("your-id")
  .Project<long>(nameof(traversalCheck1), nameof(traversalCheck2), ..., nameof(traversalCheckN), "finalUpdate")
  .By(traversalCheck1).By(traversalCheck2).By(...).By(traversalCheckN)
  .By(
      __.Start().Cast<YourVertexType>()
         .Where(traversalCheck1.Clone().Is(expectedValue1))
         .Where(traversalCheck2.Clone().Is(expectedValue2))
         .Where(traversalCheck3.Clone().Is(expectedValue3))
      /* Do real work here */
  );
```

In the final `By()` step, it's important to filter using all the traversals you've created with the values you're expecting. Also, make sure you utilize the `Clone()` method since the traversals are mutable (annoyingly so). If you don't use the clone method, you'll end up adding the `Is(###)` step to both instances within the query and give you bad results.

I realize this may be a bit to process, so hopefully this all makes sense. And even more importantly, I hope this gives you something to work with for your needs. Let me know if there is anything that is confusing or needs more clarification.

**Comment by oysteingl** [comment]
Wow, thanks for a really thorough reply!
Like you said, it's a bit too process, so I'll have to some testing of my own to fully comprehend it, but it looks like a good solution.
Have you tried using this approach in a scenario where you update properties on a vertex and add/remove edges at the same time?

**Comment by evo-terren** [comment]
Yes we have and haven't run into any shortfalls with the approach. The one thing to know about removing edges/vertices (using `drop()` step) that you'll probably need to do, though, is utilize the `sideEffect()` step so that your traversal doesn't end when using `drop()`. So, if you need to update and remove in one query, it would look something like this:

```c#
g.V("whatever")
  .Project<long>(...)
  .By(...).By(...).By(...)
  .By(
      __.Start().Cast<VertexType>()
      .Property(v => v.ETag, newEtagValue)
      .SideEffect(__.OutE(v => v.EdgeYouNeedToDelete).Drop()) //contain the drop within the side effect
      .OutV(v => v.OtherVertexThatYouCareAbout)
      .Property(v => v.OtherProperty, newPropertyValue)
  );
```

That syntax may not quite be right, but hopefully you get the idea. The side effect step is your best friend for deletes and allows you to chain a bunch of different operations in one query.

**Comment by oysteingl** [comment]
Great, thanks for all the help!
