### ISSUE TITLE
P.Within is not correctly serialized

### ISSUE THREAD

**Issue by igorgnedish** [evo-terren/Gremlin.Net.CosmosDb#32]
Try to perform following query:
g.V<MyVertex>().HasId(P.Within(new[]{"1","2"}))

Following query will be serialized:
g.V().hasLabel("my").hasId(within("[\"1\",\"2\"]"))

as you can see it uses extra quotes which makes the incorrect id parameter

**Comment by evo-terren** [comment]
Hmm. This is definitely a bug. I'll see what I can do to serialize that correctly.

In the meantime, know that there's no need to use the `within` predicate here in your particular example since `hasId` accepts multiple values, so you can simply do the following:

```
g.V().HasId("1", "2")
```

This will correctly be serialized as:

```
g.V().hasId("1", "2")
```

Again, I'll still work on getting the predicate serialized correctly as this is still a bug.

**Comment by igorgnedish** [comment]
yep, it's just an example, sorry if makes some misunderstanding. 

I have a dynamic list of ids returned from a database by a different query. So I prepared example just for a demo purposes. 

For now I have found a dirty workaround :-) but it would be really cool to have it fixed :-)

**Comment by evo-terren** [comment]
I just launched a fix with version `v0.3.3.2018-alpha`. Let me know if you still have issues with it.

**Comment by igorgnedish** [comment]
WOW! Very fast! yes, it's fixed! thank you very much! :-) 🥇
