### ISSUE TITLE
Ability to clone the traversal object or remove the side effect of on the stored ByteCode

### ISSUE THREAD

**Issue by direbearform** [evo-terren/Gremlin.Net.CosmosDb#8]
Would you consider adding an clone method to the ISchemaBoundTraversal, given that all its extension methods have side effect (I mean that when you do a = b.OutE(…), it modifies the actual byte code stored in b?

The reason asking this is if one has a shared portion of traversal that fork into different queries, it can't be done today:

prefixTrav = g.V<vert1>(id);
actTrav1 = prefixTrav.OutE('knows').InV();
actTrav2 = prefixTrav.OutE('relatesTo').InV();

The actTrav2 will have some wrong ByteCode that contains the query portion from actTrav1.

If you have a clone method, then one can do:
prefixTrav = g.V<vert1>(id);
actTrav1 = prefixTrav.Clone().OutE('knows').InV();
actTrav2 = prefixTrav.Clone().OutE('relatesTo').InV();

Or alternatively of course, make it produces no side effect at all.

**Comment by evo-terren** [comment]
Hmm. I agree with you that there should be some kind of cloning process, but I wonder if it instead should be more intrinsic to the traversals.

```c#
var initialTraversal = g.V('vertex-id');
var firstMutation = initialTraversal.OutE("some-edge");
var secondMutation = initialTraversal.InE("some-other-edge");
```

It seems like given this code, this should just work. Semantically and logically it just makes sense. `firstMutation` should result in `g.V('vertex-id').OutE('some-edge')` (which it will) and `secondMutation` should result in `g.V('vertex-id').InE('some-other-edge')`. But as you have pointed out, it won't work as intended since the bytecode object is shared when new traversal steps are added. `secondMutation` will instead be `g.V('vertex-id').OutE('some-edge').InE('some-other-edge')`.

My one worry about adding a clone extension method to the `ISchemaBoundTraversal<S, E>` object in my code is that it won't really be consistent with "regular" graph traversal objects from the standard Gremlin.Net code (This is a problem I keep running into, which only encourages me to fork their code completely and pave my own way - something I don't really have time for). I fear that people will get confused by its usage.

I'll make a deal with you: can you ask for the maintainers of Gremlin.Net to update their implementation of the `GraphTraversal<S, E>` constructor that accepts `ICollection<ITraversalStrategy>` and `Bytecode` as parameters (line 45 at time of writing: https://github.com/apache/tinkerpop/blob/master/gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversal.cs). It seems like this is where the root problem lies. I would argue that the implementation should instead be:

```c#
public GraphTraversal(ICollection<ITraversalStrategy> traversalStrategies, Bytecode bytecode)
{
    TraversalStrategies = traversalStrategies;
    Bytecode = new Bytecode(bytecode); //here's the important change
}
```

Creating a new instance of the `Bytecode` object here should do what you're asking for all traversals.

If you go this route and they tell you no, come back here, update this ticket and I'll add the clone method to my code. Sorry to give you the run around, but I truly believe that's where the change should be made.

Deal?

**Comment by evo-terren** [comment]
I should note that if you (or anyone else) wants to simply add a local extension method to your project to meet your needs instead of jumping through these hoops, it should be as simple as this:

```c#
public static ITraversal Clone(this ITraversal traversal)
{
     return new GraphTraversalSource<object, object>(new ITraversalStrategy[0], new Bytecode(traversal.Bytecode));
}
```

The only reason I hesitate in adding this to my code is that I have no way to return the same type of object. (I can't create a method with this signature: `public static T Clone(this T traversal) where T : ITraversal`). I would have no way of instantiating a new `GraphTraversal` and casting it to T. Therefore the Clone method would continue to be awkward to use. I could add one that was specific to the `ISchemaBoundTraversal<S, E>`, but then it wouldn't be available if you switched over to using `GraphTraversal<S, E>`. Hopefully I'm making sense here.

Good luck to you!

**Comment by direbearform** [comment]
Thanks a bunch. What you proposed should also work for my situation - just slightly less efficient than directly deep copy the traversal itself but that should be okay since I don't fork often.

I am not familiar with the issue escalation process with the tinkertop/gremlin.net (guess I need a pull request instead of creating an issue there?). If I figure it out, I will at least give that feedback to them - I would have preferred the traversal was written more or less in a functional style. The side effect of stepping wasn't obvious. On the other hand, if I have to guess, they probably want be more memory efficient by choosing not to do that?

I was hacking a bit in my own experiment by just duplicating the schemaboundtraversal using reflection - since for that I already know the type parameters and it worked for me. It was from that I thought of asking for clone method, since I cannot create the implementation of SchemaBoundTraversal straightly (which is declared internal).

Now I am switching to:

```c#
public static ISchemaBoundTraversal<object, T> Clone<T>(this ISchemaBoundTraversal<object, T> obj)
{
    var graphTraversal = new GraphTraversal<object, T>(new ITraversalStrategy[0], new Bytecode(obj.Bytecode));
    return graphTraversal.Cast<T>();
}
```

**Comment by direbearform** [comment]
Closing this out since above worked for me. Thank you for the help!
